global:
  mysql:
    rootPassword: "root_password"
    userPassword: "petclinic_password"
  # Define your standard defaults here
  replicas: 1
  imagePullPolicy: Always
  imageTag: "latest"
  database: "petclinic"
  databaseuser: "petclinic"
  defaultResources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m 
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3


services:
  mysql: # <--- This becomes $name
    port: 3306 # <--- This block becomes $service
    headless: true
    storage: 10Gi
    resources:  # <--- Helm sees this and ignores the global defaults!
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m 
        memory: 1Gi
    livenessProbe:
      initialDelaySeconds: 20
    imagePullPolicy: IfNotPresent
    database: "petclinic"
    prometheus: false

  config-server: # <--- Then the loop runs again, and THIS becomes $name
    port: 8888  # <--- This block becomes $service
    replicas: 1
    imagePullPolicy: IfNotPresent
    imageTag: "v1"
    prometheus: true
    
  api-gateway:
    port: 8080
    imagePullPolicy: IfNotPresent
    imageTag: "v1"
    prometheus: true

  discovery-server:
    port: 8761
    imagePullPolicy: IfNotPresent
    imageTag: "v1"
    prometheus: true

  customers-service:
    port: 8081
    imagePullPolicy: IfNotPresent
    imageTag: "v1"
    prometheus: true

  vets-service:
    port: 8083
    imagePullPolicy: IfNotPresent
    imageTag: "v1"
    prometheus: true

  visits-service:
    port: 8082
    imagePullPolicy: IfNotPresent
    imageTag: "v1"
    prometheus: true

  admin-server:
    port: 9090
    imagePullPolicy: IfNotPresent
    imageTag: "v1"
    prometheus: true