apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spring-petclinic.fullname" . }}-monitor
  labels:
    {{- include "spring-petclinic.labels" . | nindent 4 }}
    # Needs to match output of kubectl get prometheus -n monitoring ...
    release: prometheus 
spec:
  selector:
    matchLabels:
      # This ONE label finds ALL java apps and ignores MySQL
      prometheus-scrape: "true"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: http # This must match the 'name' of the port in your services.yaml
    path: /actuator/prometheus
    interval: 15s