{{- /* ========================================== */ -}}
{{- /* 1. PRE-FLIGHT VALIDATIONS                  */ -}}
{{- /* ========================================== */ -}}

{{- range $name, $service := .Values.services }}
{{- if $n := required "A valid service name is required" $name }}{{- end }}
{{- if $p := required "A valid service port is required" $service.port }}{{- end }}

{{- if not (hasKey $service "prometheus") }}
{{- fail (printf "The service %s does not have a 'prometheus' key. Please add it." $name) }}
{{- end }}


{{- /* Force port to be integer, then check if it's between 1 and 65535 */ -}}
{{- $port := int $service.port }}
{{- if and (gt $port 0) (le $port 65535) }}
  {{- /* The port is valid! */ -}}
{{- else }}
  {{- fail (printf "Invalid port '%v' for service %s. Must be between 1 and 65535." $service.port $name) }}
{{- end }}
{{- end }}

{{- /* ========================================== */ -}}
{{- /* 2. YAML GENERATION 
#1. The Label (prometheus-scrape: "true"): This is your name on the building's buzzer. It tells Prometheus,
# "Yes, I live in this cluster, and I have metrics for you." (This prevents Prometheus from wandering into the MySQL apartment).
2. The Port Name (name: http): This is your exact apartment door number. Because your ServiceMonitor is instructed to look
# for a port named http, adding - name: http to your services tells Prometheus exactly which door to knock on, 
# whether that door happens to be numbered 8080, 8081, or 8082
# ========================================== */ -}}

{{- range $name, $service := .Values.services }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- if $service.prometheus }}
    prometheus-scrape: "true"
    {{- end }}
    {{- include "spring-petclinic.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{ $name }}
     
  {{- /* The 'with' function changes the scope so we don't have to type $service.port */ -}}
  {{- with $service }}
  ports:
  # The Prometheus Port Name
  - name: http
    port: {{ .port }}
    targetPort: {{ .port }}
  {{- /* Only add clusterIP: None if 'headless: true' is defined in values.yaml */ -}}
  {{- /* If headless is missing, assume false. If it is true, print clusterIP */ -}}
  {{- if default false $service.headless }}
  clusterIP: None
  {{- end }}
  {{- end }}
---
{{- end }}