name: 'Prod Environment: Terraform Apply'
on:
  push:
    branches:
      - main
    # Only trigger this pipeline if files in these specific folders change
    paths:
      - 'terraform/environments/prod/**'
      - 'terraform/modules/**'
permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  terraform-apply-prod:
    name: 'Apply Prod'
    runs-on: self-hosted
    defaults:
      run:
        # Force all commands to run exclusively inside the Prod deployment folder
        working-directory: ./terraform/environments/prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      
      - name: Terraform Init
        run: terraform init

      # Build the infrastructure without asking for human input
      - name: Terraform Apply
        run: terraform apply -auto-approve

       # Add a comment to the PR with the results of the Terraform apply.
      
      - name: Post Sticky PR Comment (Success)
        uses: marocchino/sticky-pull-request-comment@v2
        if: success()
        with:
          header: infra-ci   # The hidden tag used to find and overwrite the comment
          message: |
            ✅ **Infrastructure CI Passed!**
            
            Results of the Terraform apply have been posted successfully to prod environment.
            [Click here to view the Actions log and details of the apply](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Post Sticky PR Comment (Failure)
        uses: marocchino/sticky-pull-request-comment@v2
        if: failure()
        with:
          header: infra-ci   # Must match the header above exactly!
          message: |
            ❌ **Infrastructure CI Failed!**
            
            The pipeline encountered an error during the Terraform apply to the prod environment.
            [Click here to view the Actions log and find the error](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})